<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Meta, title, CSS, favicons, etc. -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <?php
    echo $this->headScript()->appendFile('http://www.seekfortruelove.org/js/jquery-1.8.0.min.js', $type = 'text/javascript')
                            ->appendFile('http://www.seekfortruelove.org/js/bootstrap.min.js', $type = 'text/javascript');
    echo PHP_EOL;
    echo $this->headLink()->appendStylesheet('http://www.seekfortruelove.org/css/bootstrap.min.css');
    echo PHP_EOL;
    ?>
    <title>
        Bootstrap
    </title>

    <!-- Bootstrap core CSS -->
    <link href="http://cdnjs.bootcss.com/ajax/libs/twitter-bootstrap/2.3.1/css/bootstrap.min.css" rel="stylesheet">

    <!-- Place anything custom after this. -->
</head>
<body class="bs-docs-home">
<div class="container">
    <h1>怎么说也得搞个标题才叫模版嘛</h1>
    <?php echo $this->content;?>
</div>




</body>
</html>
