<?php $this->headLink()->appendStylesheet($this->baseUrl.'/css/post.css');?>

<div class="content">
    <div class="page-header">
        <h1>标题</h1>
    </div>

    <div class="row">
        <div class="span8">
            <h2><?php echo $this->title;?></h2>
            <?php echo $this->content;?>
            <p><a href="<?php echo $this->url('blogPost',array('action'=>'edit', 'postId'=>10));?>">click here</a></p>
        </div>
    </div>
</div>

<footer>
    <p>&copy;Company 2013</p>
</footer>


